function rmsandbox( varargin )
    if ~isempty( ver( 'fcam' ) )
        fx.maven.command.rmsandbox( varargin{:} );
    else
        thisPath = fileparts( mfilename( 'fullpath' ) );
        rmpath( fullfile(...
            thisPath,...
            'code',...
            '${artifactId}' ) );
        rmpath( fullfile(...
            thisPath,...
            'test' ) );
    end
end
